name: CI/CD Pipeline

# When to trigger the pipeline:
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build and Test
  build:
    runs-on: ubuntu-latest  # The virtual machine to run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Pulls your code to the workflow

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install from requirements file

    - name: Run tests
      run: |
        pytest  # Run your tests (ensure pytest is listed in requirements)

  # Job 2: Docker Build & Push
  docker_build:
    runs-on: ubuntu-latest
    needs: build  # Only run if the `build` job succeeds
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}  # Secret DockerHub username
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  # Secret DockerHub password
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-repo-name:latest .

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-repo-name:latest
