name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List installed packages
        run: |
          pip list  # Optional: To verify that pytest is installed

      - name: Build Docker image
        run: |
          docker build -t flask-app . || { echo 'Docker build failed'; exit 1; }

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest || { echo 'Tests failed'; exit 5; }

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t yourusername/flask-app:latest . || { echo 'Build and Push failed'; exit 1; }
          docker push yourusername/flask-app:latest

      - name: Deploy to server (optional)
        run: |
          echo "Deploying to server..."
